### ISSUE TITLE
OHC11703 -Convert to System.Version

### ISSUE THREAD

**Issue by pulkjr** [jasnic02/NetAppDocs.HealthCheckRules#6]
The rule has a false positives where if you have version 5.2.0 and 5.2 it will say they are not the same.

**Comment by jasnic02** [comment]
Added new function to compare the version strings (HealthCheckFunctions.ps1 file). It will attempt to convert to system.version where possible but fallback to a string compare. This rule will now require NetAppDocs 3.3+.
